// ===============================================
//    VERSION ULTIME AVEC DÉBOGAGE INTÉGRÉ
// ===============================================

document.addEventListener('DOMContentLoaded', async function() {
    console.log("🔄 Démarrage de l'application...");

        // 1. Configuration de Supabase - VÉRIFIEZ CES URL ET CLÉS!
            const supabaseUrl = "https://xfpkiowdevrrhsaundrz.supabase.co";
                const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcGtpb3dkZXZycmhzYXVuZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjk2MDYsImV4cCI6MjA3MjMwNTYwNn0.Lqqyo1asUKQl5AK9AElS1xwlAjLVG9uP20z2lr_wzn8";

                    // Vérification que Supabase est chargé
                        if (typeof supabase === 'undefined') {
                                console.error('❌ ERREUR: La bibliothèque Supabase nest pas chargée!');
                                        showError('Vérifiez votre connexion internet et rechargez la page.');
                                                return;
                                                    }

                                                        const sb = supabase.createClient(supabaseUrl, supabaseAnonKey);
                                                            console.log("✅ Client Supabase initialisé");

                                                                // Références aux éléments du DOM
                                                                    const qcmLoader = document.getElementById('qcm-loader');
                                                                        const qcmContent = document.getElementById('qcm-content');
                                                                            const qcmQuestion = document.getElementById('qcm-question');
                                                                                const checkAnswerBtn = document.getElementById('check-answer-btn');
                                                                                    const nextQcmBtn = document.getElementById('next-qcm-btn');

                                                                                        // Test de connexion IMMÉDIAT à Supabase
                                                                                            try {
                                                                                                    console.log("🧪 Test de connexion à Supabase...");
                                                                                                            const { data, error } = await sb.from('qcm').select('count').limit(1);
                                                                                                                    
                                                                                                                            if (error) {
                                                                                                                                        console.error('❌ Erreur de connexion Supabase:', error);
                                                                                                                                                    showError('Impossible de se connecter à la base de données. Vérifiez la console (F12) pour plus de détails.');
                                                                                                                                                                return;
                                                                                                                                                                        }
                                                                                                                                                                                
                                                                                                                                                                                        console.log("✅ Connexion Supabase réussie!");
                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                    console.error('❌ Exception lors de la connexion:', err);
                                                                                                                                                                                                            showError('Erreur de réseau ou CORS. Vérifiez les paramètres Supabase.');
                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            // Fonction pour récupérer un QCM (version ultra-simplifiée)
                                                                                                                                                                                                                                async function fetchRandomQCM() {
                                                                                                                                                                                                                                        console.log("🔄 Tentative de récupération d'un QCM...");
                                                                                                                                                                                                                                                qcmLoader.classList.remove('hidden');
                                                                                                                                                                                                                                                        qcmContent.classList.add('hidden');

                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                            // ESSAYEZ D'ABORD une requête SIMPLE sans RPC
                                                                                                                                                                                                                                                                                        const { data, error } = await sb
                                                                                                                                                                                                                                                                                                        .from('qcm')
                                                                                                                                                                                                                                                                                                                        .select('*')
                                                                                                                                                                                                                                                                                                                                        .limit(1);

                                                                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                                                                    console.error('Erreur Supabase:', error);
                                                                                                                                                                                                                                                                                                                                                                                    throw error;
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                            if (!data || data.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Error('Aucune question trouvée dans la base de données');
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('✅ QCM récupéré:', data[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                displayQCM(data[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('❌ Erreur fetchRandomQCM:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            qcmQuestion.textContent = "Erreur: " + err.message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        qcmLoader.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    qcmContent.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function displayQCM(qcm) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Votre logique d'affichage existante
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('qcm-module').textContent = qcm.module || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('qcm-question').textContent = qcm.question || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Logique pour les options...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const optionsContainer = document.getElementById('qcm-options');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            optionsContainer.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // VOTRE LOGIQUE D'AFFICHAGE DES OPTIONS ICI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            qcmLoader.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    qcmContent.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function showError(message) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const errorDiv = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            errorDiv.style.color = 'red';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    errorDiv.style.padding = '1rem';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            errorDiv.style.margin = '1rem';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    errorDiv.style.border = '1px solid red';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            errorDiv.textContent = message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.prepend(errorDiv);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Démarrage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fetchRandomQCM();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });